#pragma once

#include "Amazon/Zombies/Zombies.h"
#include "Amazon/SearchSuggestion/Suggestion.h"
#include "Amazon/Cities/Cities.h"
#include "Amazon/TwoSum/TwoSum.h"
#include "Amazon/MaxAverageSubtree/MaxAverageSubtree.h"
#include "Amazon/RepairEdges/RepairEdges.h"
#include "Amazon/Spiral/Spiral.h"
#include "Amazon/LongestPalindrome/LongestPalindrome.h"
#include "Amazon/MaxMinPath/MaxMinPath.h"
#include "Amazon/TopBuzzwords/TopBuzzwords.h"
#include "Amazon/WallsAndGates/TreasureIsland.h"
#include "Amazon/NumberClusters/NumberClusters.h"
#include "Amazon/PairWithSum/PairWithSum.h"
